# Smallest bounding box in n-dimensions:

In [40]:
import numpy as np
from media_tools import *

## A rectangle puzzle:

Suppose you have a list of random points on a line: what is the smallest range that contains the list?

In [41]:
np.random.seed(0)
points = np.random.randint(0, 10, 10)
ran = (np.min(points), np.max(points))

print("points:\n", points)
print("range:\n", ran)

points:
 [5 0 3 3 7 9 3 5 2 4]
range:
 (0, 9)


Okay, neat! So the shortest line we can plot the minimum to the maximum of all values in the list.

Let's try the same thing in two dimensions. Suppose instead of points on a line, we have random points on a plane? What is the smallest range on the plane's axes which will contain all the points?

In other words: What is the minimum bounding box for points on a two-dimensional plane.

In [47]:
np.random.seed(1)
points = np.asarray([(0, 0), (10, 10)])
dim = len(points[0])

def get_bounding_box(points):
    # find the bounding box
    bounding_box = []
    for i in range(2):
        min_val = points[0][i]
        max_val = points[0][i]
        for j in range(1, len(points)):
            min_val = min(min_val, points[j][i])
            max_val = max(max_val, points[j][i])
        bounding_box.append([min_val, max_val])
    return np.asarray(bounding_box)

ran = get_bounding_box(points)

print("points:\n", points, "\n")
print("range:\n", ran, "\n")

points:
 [[ 0  0]
 [10 10]] 

range:
 [[ 0 10]
 [ 0 10]] 



Awesome! Let's generalise our approach to n dimensional points and spaces!

## Smallest bounding-box in n-dimensions algorithm:

In [48]:
np.random.seed(1)

# generate a list of n points in n_dimensions:
def get_points(n, min=0, max=1, y_min=0, y_max=1, ndim=2):
    points = np.zeros((n, ndim))
    for i in range(n):
        for j in range(ndim):
            points[i][j] = min + (max - min) * np.random.random()
    return points

# find the bounding box
def get_bounding_box(points):
    # check how many dimensions the points have
    ndim = len(points[0])
    # find the bounding box
    bounding_box = []
    for i in range(ndim):
        min_val = points[0][i]
        max_val = points[0][i]
        for j in range(1, len(points)):
            min_val = min(min_val, points[j][i])
            max_val = max(max_val, points[j][i])
        bounding_box.append([min_val, max_val])
    return np.asarray(bounding_box)

# convert the ndim bounding box data to the point coordinates of the n dim bounding box:
def get_bounding_box_points(bounding_box):
    # check how many dimensions the points have
    ndim = len(bounding_box)
    # find every vertex of the bounding box (every combination of one value from each dimension)
    bounding_box_points = []
    for i in range(2 ** ndim):
        bounding_box_points.append([])
        for j in range(ndim):
            bounding_box_points[i].append(bounding_box[j][i % 2 ** (j + 1) // 2 ** j])
    return np.asarray(bounding_box_points)

points = get_points(10,ndim=2)
print("points:\n", points, "\n")

bounding_box = get_bounding_box(points)
print("bounding box:\n", bounding_box, "\n")

bounding_box_points = get_bounding_box_points(bounding_box)
print("bounding_box_points:\n", bounding_box_points, "\n")

points:
 [[4.17022005e-01 7.20324493e-01]
 [1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01]
 [3.96767474e-01 5.38816734e-01]
 [4.19194514e-01 6.85219500e-01]
 [2.04452250e-01 8.78117436e-01]
 [2.73875932e-02 6.70467510e-01]
 [4.17304802e-01 5.58689828e-01]
 [1.40386939e-01 1.98101489e-01]] 

bounding box:
 [[1.14374817e-04 4.19194514e-01]
 [9.23385948e-02 8.78117436e-01]] 

bounding_box_points:
 [[1.14374817e-04 9.23385948e-02]
 [4.19194514e-01 9.23385948e-02]
 [1.14374817e-04 8.78117436e-01]
 [4.19194514e-01 8.78117436e-01]] 



We did it!